# Generated by Django 4.0.2 on 2022-03-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='post/'),
        ),
    ]
