# Generated by Django 4.0.2 on 2022-03-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_localpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpost',
            name='image',
            field=models.ImageField(blank=True, default='post.jpg', upload_to='post/'),
        ),
    ]
